name: Analyze and Test our Flutter Project

on:
  pull_request:
    branches:
      - master
      

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      #Checkout the PR code
      - uses: actions/checkout@v3

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze the project
      - name: Analyze the project
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
